#!/bin/sh

echo "*** Setting Frontend environment variables ***"
export $(grep -v '^#' .env | xargs)

echo "*** Installing Frontend packages ***"
npm install --silent

echo "*** Starting Frontend React app ***"
npm start