#!/bin/sh

echo "*** Syncing with boilerplate repo ***"
git config remote.boilerplate.url >&- || git remote add boilerplate git@github.com:joaogardenberg/node-react-boilerplate.git
git pull boilerplate main