#!/bin/sh

echo "*** Syncing with base repository ***"
git config remote.base.url >&- || git remote add base git@github.com:joaogardenberg/node-react-boilerplate.git
git fetch base main
git rebase base/main
